### ISSUE TITLE
getallheaders() is not implemented

### ISSUE THREAD

**Issue by splashsky** [dunglas/frankenphp#296]
When working on a personal project, I attempted to use the built-in `getallheaders()` function to retrieve an array of all current HTTP request headers, but was met with this error:
```
Fatal error: Uncaught Error: Call to undefined function getallheaders()
```
I suppose this function was in FPM but has not been implemented in Franken yet?
https://www.php.net/manual/en/function.getallheaders.php

**Comment by BurakBoz** [comment]
You can implement this in PHP or just use the https://github.com/ralouphie/getallheaders

**Comment by splashsky** [comment]
While I can appreciate making up for the absence, a useful builtin like this probably belongs in the core runtime 😋

**Comment by dunglas** [comment]
I agree. PR welcome!

**Comment by Shikachuu** [comment]
If I'm not mistaken we are looking for [this implementation](https://github.com/php/php-src/blob/f8c2d1ec2f2e2d844484b92d9a33f3cc2defbc31/sapi/apache2handler/php_functions.c#L174), since `getallheaders()` is just an alias for this.

Tbh my C skills are non existing, yet this shouldn't be much of an issue, I think I can figure this solution out wiht a little help.

Currently I have hard a hard time figure out how to get the request headers.

I think [this struct](https://github.com/php/php-src/blob/f8c2d1ec2f2e2d844484b92d9a33f3cc2defbc31/main/SAPI.h#L50) contains the response headers.

But I'm looking for the request headers currently, I assume it has something to do with caddy because the [litespeed implementation](https://github.com/php/php-src/blob/f8c2d1ec2f2e2d844484b92d9a33f3cc2defbc31/sapi/litespeed/lsapi_main.c#L1661) looks waaaaay different, then the above mentioned apache one.

**Comment by splashsky** [comment]
Have you had any luck in the implementation @Shikachuu?

**Comment by Shikachuu** [comment]
Still stuck with the same problem mentioned above.

**Comment by withinboredom** [comment]
> Currently I have hard a hard time figure out how to get the request headers.

I think you can get them just like we get them right before flushing the response in [frankenphp.c](https://github.com/dunglas/frankenphp/blob/main/frankenphp.c#L444-L469). From there, it's (theoretically) (famous last words) just a matter of marshaling them to a PHP array and returning it.
