### ISSUE TITLE
Question about performance

### ISSUE THREAD

**Issue by thbley** [dunglas/frankenphp#382]
./frankenphp-linux-x86_64 --version
FrankenPHP v1.0.0 PHP 8.3.0 Caddy v2.7.5 h1:HoysvZkLcN2xJExEepaFHK92Qgs7xAiCFydN5x5Hs6Q=

Using non-worker mode:
```
sudo GOMAXPROCS=4 GOMEMLIMIT=10GiB GOGC=off ./frankenphp-linux-x86_64 run --config caddy.conf --adapter caddyfile php_server

caddy.conf
{
	frankenphp
	order php_server before file_server
	http_port 8080
	frankenphp {
		num_threads 64
	}
}
localhost:8080 127.0.0.1:8080 {
	root * ./
	php_server
}

index.php
<?php
echo 'test';

with:
ab -n 10000 -c 64 http://127.0.0.1:8080/

=> I get ~700 requests per second (cpu usage 45%, 2-core intel cpu with hyperthreading)
```

Using worker mode:
```
sudo GOMAXPROCS=4 GOMEMLIMIT=10GiB GOGC=off ./frankenphp-linux-x86_64 run --config caddy.conf --adapter caddyfile php_server

caddy.conf
{
	frankenphp
	order php_server before file_server
	http_port 8080
	frankenphp {
		num_threads 64
		worker index.php 16
	}
}
localhost:8080 127.0.0.1:8080 {
	root * ./
	php_server
}

index.php
<?php

do {
    $handler = static function () {
        echo 'test';
    };
// skip gc collect for this test
   \frankenphp_handle_request($handler);
} while (true);

with:
ab -n 10000 -c 64 http://127.0.0.1:8080/

=> I get ~7.5k requests per second (cpu usage 95%, 2-core intel cpu with hyperthreading)
```

Using the same with nginx/fpm I get ~2.5k requests per second.

Worker mode is great!
Is it expected that non-worker mode is much slower than fpm/nginx?

**Comment by dunglas** [comment]
The project is still in the early stages and we're working on improving performance.

The static build (unlike Docker images and non-static builds) is known to have a bug with JIT, which is disabled by default. Also, be sure that you're using the same PHP version, with the same set of extensions (by default, the static build embeds almost all PHP extensions) and the same php.ini.

In addition, many parameters can affect performance, especially in stress tests like that. Especially, the Go garbage collector may need special tuning: #366 (but I saw that you disabled it). There are also likely bugs (leaks?) and possible optimizations in the FrankenPHP core. And Caddy is known to be a bit slower (but has more features, including some improving real-life performance such as Early Hints) than NGINX, so, to test FrankenPHP only, I suggest benchmarking Caddy + FPM vs FrankenPHP.

Anyway, thanks for the benchmark! Benchmarks like this, profiles to find the bottlenecks, and of course, contributions to fix them are very welcome and will help improve performance!

**Comment by o1y** [comment]
I also compared the performance with our existing php implementation. Unfortunately, FrankenPHP is about 10 - 15% slower than the native php binaries. This is for stress test benchmarks and when serving the website in general. Is this an expected behavior or a bug? If you want, I can provide more specific details.

**Comment by dunglas** [comment]
Can you share your configuration so we can dig deeper?

**Comment by withinboredom** [comment]
I'd be curious how it holds up with 1.0.3 as well if you get a chance to test it again.

**Comment by o1y** [comment]
Sure. Here is an example repo of a dummy Laravel app (Statamic) that requires a lot of IO access, due to the architecture of the CMS (no database, based on files): https://github.com/o1y/statamic-io-performance

I use a quite simple script `response.sh`, which just records a few response times and calculates the average response, without simultaneous access.

I use php 8.3.0 in both cases. After comparing the php.ini, there are no differences regarding extensions.

## frankenphp
```
frankenphp  --version
FrankenPHP 1.0.3 PHP 8.3.1 Caddy v2.7.6 h1:w0NymbG2m9PcvKWsrXO6EEkY9Ru4FJK8uQbYcev1p3A=
```

```
frankenphp run
./response.sh

Response time [Request 1]: 1202.246000 ms
Response time [Request 2]: 982.660000 ms
Response time [Request 3]: 981.729000 ms
Response time [Request 4]: 973.847000 ms
Response time [Request 5]: 975.534000 ms
Response time [Request 6]: 983.487000 ms
Response time [Request 7]: 982.694000 ms
Response time [Request 8]: 973.386000 ms
Response time [Request 9]: 988.936000 ms
Response time [Request 10]: 971.005000 ms
Average response time: 1001.55 ms
```

## local php

```
php artisan serve
./response.sh # adjust url first

Response time [Request 1]: 929.950000 ms
Response time [Request 2]: 917.856000 ms
Response time [Request 3]: 919.921000 ms
Response time [Request 4]: 923.793000 ms
Response time [Request 5]: 915.552000 ms
Response time [Request 6]: 918.960000 ms
Response time [Request 7]: 934.299000 ms
Response time [Request 8]: 915.757000 ms
Response time [Request 9]: 914.884000 ms
Response time [Request 10]: 927.315000 ms
Average response time: 921.82 ms
```

The repo is just a constructed example. In my actual project, the execution times are even slower (around 10-15%), that's why I'm not using frankenphp in production yet. Maybe I'm doing something wrong or this slower performance is by intention, so happy about any feedback :)

**Comment by dunglas** [comment]
Can we see your php.ini files? FrankenPHP uses the official PHP engine, so there should be no difference regarding IO compared to FPM.

I suspect different configurations, missing extensions or something like that.

**Comment by o1y** [comment]
Thanks guys! I just did another comparison, but just used the exact same build config via `static-php-cli` to build a php cli, as you did in your build process. This makes the performance the same, so there's no performance overhead from frankenphp, sorry about that :)

Before, I was comparing it with the php binaries from [Laravel Herd](https://herd.laravel.com/), probably they're using a different build configuration.

**Comment by thbley** [comment]
> I use a quite simple script response.sh, which just records a few response times and calculates the average response, without simultaneous access.

I think it's normal that single thread access is slower than fpm due to overhead of TSRM (http://php.adamharvey.name/manual/ro/internals2.memory.tsrm.php).

**Comment by withinboredom** [comment]
The overhead of cgo is quite substantial (in fact, it's the dominating thing in the last profile I did of 1.0.3), and might be one reason you're seeing slower request times. Also, make sure to remove any symfony polyfills via `replace` in your `composer.json`, so if you are missing any extensions the app will crash instead of using the polyfill. 

Reducing the context switches between go/php should improve performance hugely (big chunks of output, etc). For a simple script, I was seeing over 17k reqs per sec with frankenphp on a big server, completely saturating my connection; so I suspect this is an issue with polyfills/extensions or your code vs. frankenphp being slower (though it might be, I can't test it yet). I need to upgrade my network interfaces to 10g/bit to get CPU bound to properly compare frankenphp to other SAPIs, which is something I hope to have done by Q2.

**Comment by dunglas** [comment]
Handled in https://github.com/dunglas/frankenphp/issues/481.
