### ISSUE TITLE
Frankenphp is using the wrong `php.ini` file

### ISSUE THREAD

**Issue by 121593** [dunglas/frankenphp#386]
The documentation does not explicitly states where the `php.ini` file in use is located.

If I log into the frankenphp Docker container and `echo $PHP_INI_DIR` I see `/usr/local/etc/php`.

But modifications of `/usr/local/etc/php/php.ini` are not picked by PHP behind Caddy, even though they can be seen by running `php -r "phpinfo();" | grep memory`.

Then if I run `find / -name "php.ini"` I see files in 
```
/app/docker/php/php.ini
/app/php.ini
```

And modifying the `/app/php.ini` file works as intended.

The Config page in the docs probably needs to say a bit more about that topic.

I would do a PR but not quite sure what to say.

**Comment by withinboredom** [comment]
I wouldn't say that it is misleading, as it _should_, theoretically, be using the php.ini file from `$PHP_INI_DIR` and more likely a bug or misconfiguration somewhere.

I just pulled `dunglas/frankphp:latest`, started the container with bash, copied the production php.ini to php.ini, edited `$PHP_INI_DIR/php.ini`, changed a variable (`memory`), started `frankenphp -c /etc/caddy/Caddyfile start`, then `curl -k https://localhost` and verified my changes were there, and they are.

Can you provide a Dockerfile or some way to reproduce the issue you are seeing? I'm unable to reproduce it using the steps I provided.

**Comment by 121593** [comment]
Yes indeed the issue was probably misworded.

I managed to make a reproduction [there](https://github.com/121593/repro-frankenphp-386).

**Comment by withinboredom** [comment]
Ah, I think the issue is this line: https://github.com/121593/repro-frankenphp-386/blob/57ab0bec39f10ec4cc65c68c9821382396ce3a6b/Dockerfile#L12

```Dockerfile
RUN sed -i "s/128/512/" /usr/local/etc/php/php.ini
```

sed runs on the entire line, otherwise it would replace all instances of 128 with 512, which is probably not what you intend by default. This is probably closer to what you want:

```Dockerfile
RUN sed -i "s/memory_limit = 128M/memory_limit = 512M/" $PHP_INI_DIR/php.ini
```

**Comment by 121593** [comment]
Sure this statement has a broad impact and I'd never use it that way in a real life app but it is not relevant to the issue.

Here the reproduction shows that the config file read by SAPI (or whatever is behind Caddy) is different that the one picked up by the CLI ; regardless to the content of this file.

**Comment by withinboredom** [comment]
Each SAPI may have it's own php.ini. This is the default in ubuntu installations, if I recall. At least on my machine I have `/etc/php/8.3/cli/php.ini` and `/etc/php/8.3/fpm/php.ini`. That's not a bug, but by design.

I looked in `$PHP_INI_DIR/php.ini` and saw the 512mb limit, and saw it on `https://localhost`. 

![image](https://github.com/dunglas/frankenphp/assets/1883296/8052b51a-6ccf-4886-b600-43e042be759b)

I do not have an `/app/php.ini` 

```
docker ps
CONTAINER ID   IMAGE                        COMMAND                  CREATED         STATUS                   PORTS                                                              NAMES
da5732d1439c   repro-frankenphp-386-frank   "docker-php-entrypoi…"   3 minutes ago   Up 3 minutes (healthy)   80/tcp, 2019/tcp, 443/udp, 0.0.0.0:443->443/tcp, :::443->443/tcp   repro-frankenphp-386-frank-1

docker compose exec frank bash
root@da5732d1439c:/app# ls        
Dockerfile  LICENSE  README.md	bin  composer.json  composer.lock  config  docker-compose.yaml	public	src  symfony.lock  var	vendor
```

I can't reproduce the issue you are seeing.

**Comment by 121593** [comment]
Just tried the whole thing again and I am seeing the expected value on localhost.

I don't understand where I mixed up things so I'll just close the issue and reopen it if I understand what is going on.

Thx for the attention tho.

**Comment by withinboredom** [comment]
Is it possible that you had another container running on the same port? Docker will sometimes silently continue without letting you know that the ports couldn't be forwarded.
