### ISSUE TITLE
Argon2 support

### ISSUE THREAD

**Issue by josecl** [dunglas/frankenphp#410]
While I was testing in Laravel I got this error:

```
Fatal error: Uncaught Error: Undefined constant "PASSWORD_ARGON2ID"
````

According to PHP documentation: "This algorithm is only available if PHP has been compiled with Argon2 support."
https://www.php.net/manual/en/function.password-hash.php

Tested in `v1.0.0` and  `v1.0.1`, both `linux-x86_64` and `mac-arm64`.

**Comment by crazywhalecc** [comment]
Hi @dunglas, I noticed you posted version 1.0.2 on Twitter mentioning this issue. Adding the sodium extension does not solve this problem, because PHP's `password_hash()` uses libargon2, not libsodium (also mentioned in the official PHP documentation above).

Last week I merged @mpociot's libargon2 [PR](https://github.com/crazywhalecc/static-php-cli/pull/64) and also mentioned in [docs](https://static-php.dev /en/guide/extension-notes.html#password-argon2).
