### ISSUE TITLE
information of benchmark and memory usage?

### ISSUE THREAD

**Issue by denisdemaisbr** [dunglas/frankenphp#444]
any info ?

**Comment by withinboredom** [comment]
Benchmarks largely depend on your application (you are most likely to be CPU/IO bound by your database/workload rather than the web server). That being said, we're seeing a reported 15%-ish increase in speed for most workloads in worker mode. After #442 is merged, memory usage will be much lower than it currently is.

**Comment by dunglas** [comment]
Handled in https://github.com/dunglas/frankenphp/issues/481.
