### ISSUE TITLE
Download failed when using add-package

### ISSUE THREAD

**Issue by krystof018** [dunglas/frankenphp#580]
### What happened?

I was trying to install this module on my caddy instance and I was unable to do so, because of this error: 
/# `caddy add-package github.com/dunglas/frankenphp/caddy`
```
2024/02/15 22:58:24.088 INFO    this executable will be replaced        {"path": "/usr/bin/caddy"}
2024/02/15 22:58:24.088 INFO    requesting build        {"os": "linux", "arch": "arm64", "packages": ["github.com/dunglas/frankenphp/caddy"]}
Error: download failed: download failed: HTTP 400: unable to fulfill download request (id=def3bbd7-c4c8-4461-83dc-187d6f1d44ed)
```

I tried to run this on multiple servers but with the same result. 

### Build Type

Docker (Debian Bookworm)

### Worker Mode

Yes

### Operating System

GNU/Linux

### CPU Architecture

aarch64

### Relevant log output

```shell
2024/02/15 22:58:24.088 INFO    this executable will be replaced        {"path": "/usr/bin/caddy"}
2024/02/15 22:58:24.088 INFO    requesting build        {"os": "linux", "arch": "arm64", "packages": ["github.com/dunglas/frankenphp/caddy"]}
Error: download failed: download failed: HTTP 400: unable to fulfill download request (id=def3bbd7-c4c8-4461-83dc-187d6f1d44ed)
```

**Comment by dunglas** [comment]
This command is part of Caddy (not FrankenPHP) and isn't supporting the FrankenPHP module because it relies on cgo, which isn't supporter by the Caddy API.

We should disable this command (as well as the self-update command) in our builds, if possible.

To install extra packages, you have to rely on `xcaddy`: https://frankenphp.dev/docs/docker/#how-to-install-more-caddy-modules
