### ISSUE TITLE
FrankenPHP does not work with symfony ux autocomplete

### ISSUE THREAD

**Issue by pyatnitsev** [dunglas/frankenphp#683]
### What happened?

Sentry log is

<img width="1146" alt="image" src="https://github.com/dunglas/frankenphp/assets/4361764/52b01659-9aa0-480c-b314-1046618c1d12">

I use https://ux.symfony.com/autocomplete with standard doctrine.
first request when coursor pointed to field was ok, but no one more. All next requests ends with 500 error with log, that I have attached above.

This issue related to worker mode. I disable it, now autocomplete works file. 

So, I can create a minimal app, that reproduce issue.

### Build Type

Docker (Alpine)

### Worker Mode

Yes

### Operating System

GNU/Linux

### CPU Architecture

x86_64

### PHP configuration

```shell
I use latest PHP version of official docker image.
```

**Comment by withinboredom** [comment]
It looks like this library won't support worker mode and needs to be architected so that information isn't shared between requests. In this case, it looks like it registers a singleton in the container, expecting it to be cleaned up after the request is done.

This isn't a frankenphp bug, you should open an issue [with them](https://github.com/symfony/ux/issues)

**Comment by bpacholek** [comment]
Hi @pyatnitsev I can confirm what @withinboredom said that this is related to the fact that these instances are not re-set on each request when in worker mode which causes `setOptions` to be executed on a preconfigured form. As a temporary workaround I have suggested a decorator in the `symfony/ux` issue log:
https://github.com/symfony/ux/issues/1649#issuecomment-2234864882
